### ISSUE TITLE
feat: plotting utilities

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uhi#12]
It would be useful to have two new runtime accessible items in UHI:

NumPyPlottableHistogram (from https://github.com/scikit-hep/mplhep/pull/251, though called NumPyPlottableProtocol there, which is technically incorrect, it's not a Protocol, it just satisfies one). This could be used by libraries (like mplhep, histoprint) to simplify usage - they would _only_ support PlottibleHistogram, and then could adapt any non-PlottibleHistogram legacy code (like NumPy tuples) with NumPyPlottableHistogram. Which leads to the second new addition:

A new function, `uhi.ensure_plottable_histogram` (name open for debate), that converts known Histogram types that do not support PlottibleHistogram (NumPy tuples, at least, probably PyROOT could be supported too) into a NumPyPlottableHistogram, and lets existing PlottableHistogram's pass through. It always returns a PlottableHistogram. It would essentially be `hist_object_handler` in from mplhep. It's very similar in idea to `os.fspath()`.

CC @andrzejnovak and @ast0815. The only requirement for UHI beyond the stdlib or stdlib backports is that it's Python 3.6+. This would likely be intentionally designed to be easy to copy out and use standalone or use as an implementation example, if a user didn't want to add a dependency.

**Comment by ast0815** [comment]
Looks like a useful addition to me. Right now I copied the code from `mplhep` into `histoprint` because I did not want the additional dependencies that come with that package.
